# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: bash
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1


plugins: [jekyll-paginate-v2, jekyll-seo-tag, match_regex, jekyll-feed]

pagination:
  enabled: true
  per_page: 4
  permalink: "/page/:num/"
  sort_reverse:   true # this is the key to sort posts in reverse chronological order

comments: true

source: source
destination: _site
sass:
  sass_dir: assets/_sass
  style: compressed # expanded

# SEO settings
title: Espoir Murhabazi ideas' home
description: "Murhabazi Buzina Espoir Home on the internet"
keywords: "Espoir Murhabazi, Congolese Software Engineer, Ingenieur Informaticien Congolais, Geek Corner, Murhabazi Buzina"
url: https://murhabazi.com
baseurl: ""

google_analytics: UA-223988765-1
repo: https://github.com/espoirMur/espoirMur.github.io
disqus_shortname: "espoirmurhabazi"
disqus_site_shortname: "espoirmurhabazi"

# Author settings
author:
  name: Murhabazi Buzina Espoir
  job: Machine Learning Engineer
  bio: "Congolese Machine Learning Engineer"
  thumb: /assets/images/me.jpg
  profile-pic: /assets/images/me-official-speaker.jpg
  twitter: esp_py
  logo: /assets/images/me.ico
# navbar pages
navbar:
  - slug: about
    title: whoami();
  - slug: blog
    title: read();
  - slug: schedule
    title: schedule();
  - slug: learnings
    title: learnings();


exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile", 'vendor']

social:
  name: Espoir Murhabazi
  links:
    -  https://github.com/espoirMur
    -  https://twitter.com/esp_py
    -  https://www.linkedin.com/in/espoirMur/
    -  https://stackoverflow.com/users/4683950/espoir-murhabazi

feed:
  posts_limit: 20
  disable_in_development: true
